#application.yml
spring:
  datasource:
    url: jdbc:mysql://db:3306/inventory_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
    username: appuser1
    password: very_secret_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none          # エンティティ定義からテーブル自動更新 update 今回はnone
    # show-sql: true
    # defer-datasource-initialization: true   # ★ schema作成→data.sql の順にする
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # ★警告が気になるなら削除してもOK

  sql:
    init:
      mode: never              # always ★ MySQL など外部DBでも data.sql を必ず実行
  
  # Spring Security のログ（DEBUG）
  logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    